### ISSUE TITLE
Generated Results are not consistent with original MVDream repos.

### ISSUE THREAD

**Issue by Colezwhy** [ashawkey/mvdream_diffusers#6]
Hi, thank you for your great job, that helps a lot.
But I wonder when I use MVDream pipeline in this repo as a baseline, it does not provide similar generated images as the original MVDream repo will produce, would you please give me some suggestions on it? 
Thank you very much!

**Comment by snowflakewang** [comment]
Hi, I miss the same issue. Could you please provide some suggestions? Thank you!

**Comment by Colezwhy** [comment]
> Hi, I miss the same issue. Could you please provide some suggestions? Thank you!

Nah, I simply gave it up. Though not exactly the same, the generated images show similar properties. And that is not a big problem in my experiments.
